(function(){function d(d,b,B,f){return isNaN(d)?b:d<B?B:d>f?f:d}function za(d,b){for(var f={},I=1;4>I;I++){var J=d["wave"+I];if(J)for(var s in J)!isNaN(J[s])&&s in Aa&&(f[Aa[s]+I]=J[s])}if(b)for(s in Va)s in f||(f[s]=0);return f}function U(T,b){function B(a){a=l.width=V.clientWidth;var b=l.height=V.clientHeight;Ba&&(ha=b/a>Ma?a/Ca:b/Da);K&&(W=w+t*a,X=u+v*b)}function I(a,b,c){c=ia/(ja+c);return{x:c*a,y:c*b,alpha:1>c?c*c:1,scale:c}}function J(){var a,b,d,e,f,k,h;Y=Math.sqrt(C*C+D*D);n=C/Y||1E-4;p=-D/
Y||1E-4;Z=Math.sin(c.angle);L=Math.cos(c.angle);e=[[n*n+p*p*L,n*p*(1-L),p*Z],[n*p*(1-L),p*p+n*n*L,-n*Z],[-p*Z,n*Z,(n*n+p*p)*L]];h=q;var m=[],g;for(g=0;3>g;g++)for(m[g]=[],a=0;3>a;a++)m[g][a]=e[g][0]*h[0][a]+e[g][1]*h[1][a]+e[g][2]*h[2][a];q=m;l.width=l.width;M.fillStyle=ka;K?M.translate(l.width/2+W,l.height/2+X):M.translate(l.width/2,l.height/2);Ba&&M.scale(ha,ha);for(m=la;m--;)for(e=m/la*da-Na,g=h=Math.round(la*Math.cos(e)*2);g--;)a=g/h*2*da-da,d=($+c.amp1*Math.sin(c.freq1*e+c.pha1))*Math.cos(e)*
Math.cos(a),f=($+c.amp2*Math.sin(c.freq2*a+c.pha2))*Math.cos(e)*Math.sin(a),k=($+c.amp3*Math.sin(c.freq3*e+c.pha3))*Math.sin(e),a=q[0][0]*d+q[0][1]*f+q[0][2]*k,b=q[1][0]*d+q[1][1]*f+q[1][2]*k,d=q[2][0]*d+q[2][1]*f+q[2][2]*k,a=I(a,b,d),b=ma*a.scale,M.globalAlpha=a.alpha,0<b&&M.fillRect(a.x,a.y,b,b)}function s(a){var b=l.getBoundingClientRect();return{x:a.clientX-b.left-W,y:a.clientY-b.top-X}}function na(a){oa=(new Date).getTime();oa-Ea>1E3/Oa&&(m=s(a),N=m.x-pa,O=m.y-qa,P=Math.sqrt(N*N+O*O),ea=Math.sqrt((m.x-
l.width/2)*(m.x-l.width/2)+(m.y-l.height/2)*(m.y-l.height/2)),P&&ea<Q&&(ra=ea<x?1:(Q-ea)/(Q-x),Math.abs(Math.acos((N*Fa+O*Ga)/(Ha*P)))>Math.PI/2&&(R*=-1),Math.min(P,Ia)*E*ra>Math.abs(c.angle)&&(Ja.stop(),c.angle=R*Math.min(P,Ia)*E*ra,D=R*N,C=R*O,Ja=Pa.run(c,{angle:R*fa},f.powOut(3),sa,F)),Fa=N,Ga=O,Ha=P),pa=m.x,qa=m.y,Ea=oa)}function aa(a){document.removeEventListener("mousemove",aa);m=s(a);pa=m.x;qa=m.y;document.addEventListener("mousemove",na)}var ta=document.getElementById(T);if(ta){U.instances[T]&&
U.instances[T].destroy();U.instances[T]=this;b||(b={});var e=Number.POSITIVE_INFINITY,G=Number.NEGATIVE_INFINITY,Oa=30,Ia=100,da=Math.PI,Na=da/2,la="DETALIZATION"in b?d(b.DETALIZATION,60,1,e):d(b.DETALISATION,60,1,e),$=d(b.BLOB_SIZE,220,1,e),ba=d(b.BLOB_DISTANCE,1E3,0,e),fa=d(b.ROTATION_SPEED,5,0,e)/1E3,y=d(b.PERSPECTIVE_DISTORTION,1,.001,e),w=d(b.OFFSET_X,0,G,e),u=d(b.OFFSET_Y,0,G,e),t=d(b.PERCENTAGE_OFFSET_X,0,G,e)/100,v=d(b.PERCENTAGE_OFFSET_Y,0,G,e)/100,ma=d(b.DOT_SIZE,2,0,e),ka=b.DOT_COLOR||
"black",Ba=b.AUTO_SCALE,Ca=d(b.VIEWPORT_WIDTH,800,100,e),Da=d(b.VIEWPORT_HEIGHT,800,100,e),x=d(b.MOUSE_DISTANCE_MIN,20,0,e),Q=d(b.MOUSE_DISTANCE_MAX,x+400,x+.001,e),E=d(b.MOUSE_SENSITIVITY,1,0,e)/1E3,sa=1E3*d(b.INERTIAL_TIME,2,0,e),Qa=b.INITIAL_SHAPE||{wave1:{amplitude:70,frequency:3,phase:0},wave2:{amplitude:60,frequency:2,phase:0},wave3:{amplitude:50,frequency:2,phase:0}},ga=b.USE_MORPHING,ua=b.USE_WAVE_MOTION,Ka=b.USE_WAVE_SWING,Ra="MORPHING_AUTOPLAY"in b?b.MORPHING_AUTOPLAY:!0,La=d(b.MORPHING_DURATION,
2,0,e),Sa=d(b.MORPHING_DELAY,1,0,e),S=b.MORPHING_TRANSITION_TYPE||"cubic",g=b.MORPHING_SHAPES||[];if(ua&&ga&&g.length)for(var r=1;4>r;r++)if(b["WAVE_"+r+"_MOTION_SPEED"])for(var k=g.length;k--;){var ca=g[k]["wave"+r];ca&&"phase"in ca&&delete ca.phase}if(Ka)for(r=1;4>r;r++){var z=b["WAVE_"+r+"_SWING_SETTINGS"];if(z){for(var H in z){var h=z[H];if(h){if(ga)for(k=g.length;k--;)(ca=g[k]["wave"+r])&&H in ca&&delete ca[H];"type"in h&&(h.wave=("function"===typeof h.type?h.type:Wa[h.type])||va.sin,delete h.type);
"amplitude"in h&&isNaN(h.amplitude)&&delete h.amplitude;"frequency"in h&&isNaN(h.frequency)&&delete h.frequency;"phase"in h&&isNaN(h.phase)&&delete h.phase}}z.phase&&ua&&(b["WAVE_"+r+"_MOTION_SPEED"]=0)}}var wa=b.WAVE_1_MOTION_SPEED,xa=b.WAVE_2_MOTION_SPEED,ya=b.WAVE_3_MOTION_SPEED,ja=ba/y,ia=1E3/y,V=function(){var a=document.createElement("div");Ta.set(a,{position:"relative",width:"100%",height:"100%",top:0,left:0,margin:0,userSelect:"none",MozUserSelect:"none",WebkitUserSelect:"none",MsUserSelect:"none",
KhtmlUserSelect:"none",userDrag:"none",WebkitUserDrag:"none",overflow:"hidden",cursor:"default"});a.setAttribute("unselectable","on");ta.appendChild(a);return a}(),l=function(){var a=document.createElement("canvas");Ta.set(a,{position:"absolute",width:"100%",height:"100%",top:0,left:0,margin:0});V.appendChild(a);return a}(),M=l.getContext("2d"),F=new Xa,c=function(){var a={set:function(a){for(var b in a)this[b]=a[b]},angle:fa},b=za(Qa,!0),c;for(c in b)a[c]=b[c];return a}(),D=5,C=5,R=1,Ja={stop:function(){}},
Z=Math.sin(c.angle),L=Math.cos(c.angle),Y=Math.sqrt(C*C+D*D),n=C/Y,p=-D/Y,q=[[1,0,0],[0,1,0],[0,0,1]],ea,ra,m,Fa=0,Ga=0,Ha=0,N,O,P,pa,qa,oa,Ea=(new Date).getTime(),A,ha,W=0,X=0,K=w||u||t||v,Ma=Da/Ca;this.resize=function(){B()};this.destroy=function(){U.instances[T]=null;F.removeAllListeners();A&&A.clear();window.removeEventListener("resize",B);document.removeEventListener("mousemove",aa);document.removeEventListener("mousemove",na);V.removeChild(l);ta.removeChild(V);ta=T=b=e=Oa=Ia=da=Na=la=$=fa=y=
ma=ka=x=Q=E=sa=Qa=ga=ua=Ka=Ba=Ca=Da=Ra=La=Sa=S=g=wa=xa=ya=ba=ja=ia=w=u=t=v=V=l=M=F=c=D=C=R=Ja=Z=L=Y=n=p=q=ea=ra=m=Fa=Ga=Ha=N=O=P=pa=qa=oa=Ea=A=Ma=ha=B=I=J=s=na=aa=K=W=X=null;for(H in this)delete this[H];this.resize=this.destroy=this.morphTo=function(){}};this.morphTo=function(a){if(ga&&g.length){var b;a&&"object"===typeof a?b=a:!isNaN(a)&&0<=a&&a<g.length&&!(a-Math.floor(a))&&(b=g[a]);b&&Pa.run(c,za(b),"function"===typeof S?S:Ua[S],1E3*La,F)}};Object.defineProperties(this,{blobSize:{get:function(){return $},
set:function(a){$=d(a,220,1,e)},configurable:!0},blobDistance:{get:function(){return ba},set:function(a){ba=d(a,1E3,0,e);ja=ba/y;ia=1E3/y},configurable:!0},rotationSpeed:{get:function(){return fa},set:function(a){c.angle=fa=d(a,5,0,e)/1E3},configurable:!0},perspectiveDistortion:{get:function(){return y},set:function(a){y=d(a,1,.001,e);ja=ba/y;ia=1E3/y},configurable:!0},offsetX:{get:function(){return w},set:function(a){K=(w=d(a,0,G,e))||u||t||v;W=w+t*l.width},configurable:!0},offsetY:{get:function(){return u},
set:function(a){u=d(a,0,G,e);K=w||u||t||v;X=u+v*l.height},configurable:!0},percentageOffsetX:{get:function(){return 100*t},set:function(a){t=d(a,0,G,e)/100;K=w||u||t||v;W=w+t*l.width},configurable:!0},percentageOffsetY:{get:function(){return 100*v},set:function(a){v=d(a,0,G,e)/100;K=w||u||t||v;X=u+v*l.height},configurable:!0},dotSize:{get:function(){return ma},set:function(a){ma=d(a,2,0,e)},configurable:!0},dotColor:{get:function(){return ka},set:function(a){ka=a||"black"},configurable:!0},mouseDistanceMin:{get:function(){return x},
set:function(a){x=d(a,20,0,Q-1E-4)},configurable:!0},mouseDistanceMax:{get:function(){return Q},set:function(a){Q=d(a,x+400,x+.001,e)},configurable:!0},mouseSensitivity:{get:function(){return E},set:function(a){var b=E;(E=d(a,1,0,e)/1E3)&&!b?document.addEventListener("mousemove",aa):b&&!E&&(document.removeEventListener("mousemove",aa),document.removeEventListener("mousemove",na))},configurable:!0},inertialTime:{get:function(){return sa},set:function(a){sa=1E3*d(a,2,0,e)},configurable:!0},wave1Amplitude:{get:function(){return c.amp1},
set:function(a){c.amp1=a},configurable:!0},wave2Amplitude:{get:function(){return c.amp2},set:function(a){c.amp2=a},configurable:!0},wave3Amplitude:{get:function(){return c.amp3},set:function(a){c.amp3=a},configurable:!0},wave1Frequency:{get:function(){return c.freq1},set:function(a){c.freq1=a},configurable:!0},wave2Frequency:{get:function(){return c.freq2},set:function(a){c.freq2=a},configurable:!0},wave3Frequency:{get:function(){return c.freq3},set:function(a){c.freq3=a},configurable:!0},wave1Phase:{get:function(){return c.pha1},
set:function(a){c.pha1=a},configurable:!0},wave2Phase:{get:function(){return c.pha2},set:function(a){c.pha2=a},configurable:!0},wave3Phase:{get:function(){return c.pha3},set:function(a){c.pha3=a},configurable:!0}});window.addEventListener("resize",B);B();if(ga&&Ra&&g.length){A=new Ya;A.delay=Sa;k=0;for(z=g.length;k<z;k++)A.addTween(c,za(g[k]),"function"===typeof S?S:Ua[S],La,F);A.addQueue(A);A.run()}ua&&(k=function(){var a={},b=0;wa&&!isNaN(wa)&&(a.pha1=wa,b++);xa&&!isNaN(xa)&&(a.pha2=xa,b++);ya&&
!isNaN(ya)&&(a.pha3=ya,b++);return b?new Za(c,a,F):0}())&&k.play();if(Ka)for(k=1;4>k;k++)if(z=b["WAVE_"+k+"_SWING_SETTINGS"])for(H in z)(r=Aa[H])&&(new $a(c,r+k,z[H],F)).play();F.addListener(J);E&&document.addEventListener("mousemove",aa)}else alert("BlobAnimation ERROR: There is no element with the specified id")}var Xa=jsband.Metronome,f=jsband.Ease,Pa=jsband.Tween,Ta=jsband.CssProp,Ya=jsband.Queue,$a=jsband.Swing,va=jsband.Wave,Za=jsband.Motion,Ua={linear:f.lin(),quad:f.pow(2),cubic:f.pow(3),quart:f.pow(4),
quint:f.pow(5),circ:f.circ(),sine:f.sin(),expo:f.exp(),elastic:f.osc2Out(),bounce:f.bncOut(),back:f.backOut()},Wa={sine:va.sin,linear:va.triangle,pulse:va.pulse},Va={amp1:1,freq1:1,pha1:1,amp2:1,freq2:1,pha2:1,amp3:1,freq3:1,pha3:1},Aa={amplitude:"amp",frequency:"freq",phase:"pha"};U.instances={};window.BlobAnimation=U})();
